// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogContent: typeof import('./../src/components/dialog-content/index.vue')['default']
    IconFont: typeof import('./../src/components/icon-font/icon-font.vue')['default']
    IconFontSymbol: typeof import('./../src/components/icon-font/icon-font-symbol.vue')['default']
    MessageContent: typeof import('./../src/components/message-content/index.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    PointerPopover: typeof import('./../src/components/pointer-popover/index.vue')['default']
    Provider: typeof import('./../src/components/app-provider/provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowAnimation: typeof import('./../src/components/show-animation/index.vue')['default']
    UploadImage: typeof import('./../src/bizComponents/dialogs/upload-image.vue')['default']
  }
}
