name: sync to gitlab
on: [push, create, delete]
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
            echo "Home: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"

  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync GitHub to GitLab Action
        uses: adambirds/sync-github-to-gitlab-action@v1.1.0
        with:
          destination_repository: ssh://git@gitlab.openviewtech.com:10022/moyu-chat/develop-applet.git
          destination_branch_name: "${GITHUB_REF}"
          destination_ssh_key: ${{ secrets.GITLAB_SYNC }}
